export const RobotActionTypes = {
    FETCH_ROBOTS_START: 'FETCH_ROBOTS_START',
    FETCH_ROBOTS_SUCCESS: 'FETCH_ROBOTS_SUCCESS',
    FETCH_ROBOTS_FAILURE: 'FETCH_ROBOTS_FAILURE',
    FILTER_ROBOTS: 'FILTER_ROBOTS'
}